package com.istech.lighthouse.model.ongoingdata

data class Data(
    val consumerID: Int,
    val createdDate: String,
    val fr: String,
    val i: String,
    val i1: String,
    val i2: String,
    val i3: String,
    val msno: String,
    val pF1: String,
    val pF2: String,
    val pF3: String,
    val pf: String,
    val registersID: Int,
    val rtc: String,
    val updatedDate: String,
    val v: String,
    val v1: String,
    val v2: String,
    val v3: String,
    val vA1: String,
    val vA2: String,
    val vA3: String,
    val va: String,
    val vaR1: String,
    val vaR2: String,
    val varr: String,
    val w: String,
    val w1: String,
    val w2: String,
    val w3: String
)